### ISSUE TITLE
Varnish xkey

### ISSUE THREAD

**Issue by shyim** [mothership-gmbh/headless-shopware-varnish-cache#1]
You should really look into using Varnish xkey. https://github.com/varnish/varnish-modules/blob/master/src/vmod_xkey.vcc

It's much better than abusing headers for the cache keys :). It can perform also A LOT of tags at once

**Comment by niklaswolf** [comment]
You are completely right and that's also on our list!
Apparently our hoster doesn't support xkeys right now (at least that's what a comment in our full internal varnish config which I didn't write) says.
But we know, that this would be better and that it exists :)

**Comment by niklaswolf** [comment]
Just for reference, I'll add this here: 
Since Shopware 6.4.17.0. the ReverseProxy for the storefront also support xkey. We can adapt this, maybe the whole bundle itself can be replaced by the official solution :) 

https://github.com/shopware/platform/blob/trunk/src/Storefront/Framework/Cache/ReverseProxy/VarnishReverseProxyGateway.php
